FROM node:16-alpine as build-phase

WORKDIR /app

ENV PATH="node_modules/.bin:$PATH"
ENV NODE_ENV=development

COPY ["package-lock.json", "package.json", "./"]
RUN npm i && npm cache clean --force

COPY ./ ./
RUN npm run build