FROM node:16-alpine as build-stage

WORKDIR /app

ENV PATH="node_modules/.bin:$PATH"
ENV NODE_ENV=development

COPY ["package-lock.json", "package.json", "./"]

COPY ./ ./
RUN npm i && npm cache clean --force

RUN npm run build

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf