FROM node:16-alpine as build-phase

WORKDIR /app

ENV PATH="node_modules/.bin:$PATH"
ENV NODE_ENV=development

# RUN npm install nodemon

COPY [".*", "package*.json", "*conf*", "./"]
# COPY ./ ./
RUN npm i && npm cache clean --force